baseurl: ""
url: ""
sass:
  sass_dir: assets/css/sass

# Logo settings
logodescription: Wellington Heritage Weekend

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

collections_dir: _collections

collections:
  events:
    permalink: /event/:title/
    output: true
  hotels:
    permalink: /hotel/:title/
    output: true
  posts:
    permalink: /post/:title/
    output: true

exclude: [".idea/", ".gitignore", "LICENSE.txt"]
include: [_pages]

url: 'https://wellingtonheritageweek.co.nz'
