title: Wellington Heritage Week
description: "Experience Wellington's people, places & stories during Wellington
  Heritage Week. "
analytics: ""
show_events: false
show_hotel: false
banner-title: ""
banner: /assets/uploaded/whw-2023-dates_4k.jpg
