title: Wellington Heritage Week
description: >-
  Experience Wellington's people, places & stories during Wellington Heritage
  Week 2018 22-28 October. 
analytics: ''
show_events: true
banner-title: ''
banner: /assets/uploaded/banner.jpg
