title: Wellington Heritage Week
description: "Experience Wellington's people, places & stories during Wellington
  Heritage Week 2022, 24 Oct - 6 Nov. "
analytics: ""
show_events: false
show_hotel: false
banner-title: ""
banner: /assets/uploaded/whw-2022-dates_4k.jpg
