title: Wellington Heritage Week
description: >-
  Experience Wellington's people, places & stories during Wellington Heritage
  Week 2019 28 Oct - 3 Nov. 
analytics: ''
show_events: false
banner-title: ''
banner: /assets/uploaded/whw-logo-2019.png
