title: Wellington Heritage Week
description: "Experience Wellington's people, places & stories during Wellington
  Heritage Week 2021 25 - 31 Oct. "
analytics: ""
show_events: true
show_hotel: true
banner-title: ""
banner: /assets/uploaded/whw-logo-2021.png
