backend:
  name: github
  repo: Wellington-Heritage-Week/Wellington-Heritage-Week.github.io
  branch: master
  base_url: https://wellington-heritage-week.herokuapp.com

publish_mode: editorial_workflow
media_folder: "assets/uploaded"

collections:
  - name: "events"
    label: "Events"
    folder: "collections/_events/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Event date", name: "event_date", widget: "string"}
      - {label: "Booked out", name: "booked_out", widget: "boolean"}
      - label: "Host information"
        name: "host"
        widget: "object"
        fields:
          - {label: "Host image", name: "image", widget: "image"}
          - {label: "Host name", name: "name", widget: "string"}
          - {label: "Blurb", name: "blurb", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone number", name: "phone", widget: "string"}
          - {label: "Website (remember http://)", name: "website", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tag"
        widget: "list"
        allow_add: false
        default: []
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site settings"
        name: "site"
        file: "_config.yml"
        fields:
          - {label: "Site title", name: "title", widget: "text"}
          - {label: "Homepage title", name: "banner-title", widget: "text"}
          - {label: "Homepage description", name: "banner-desc", widget: "text"}
          - {label: "Author image", name: "author-pic", widget: "image"}
          - {label: "Author name", name: "author-name", widget: "text"}
          - {label: "Author about", name: "about-author", widget: "text"}
          - {label: "Author email", name: "email", widget: "text"}
          - {label: "Phone", name: "phone", widget: "text"}
          - {label: "Website", name: "website", widget: "text"}
          - {label: "Facebook url", name: "facebook_url", widget: "text"}
          - {label: "Instagram url", name: "instagram_url", widget: "text"}
          - {label: "Analytics tracking tag", name: "analytics", widget: "text"}
          - {label: "Show events", name: "show_events", widget: "boolean"}