backend:
  name: github
  repo: Wellington-Heritage-Week/Wellington-Heritage-Week.github.io
  branch: master
  base_url: https://wellington-heritage-week.herokuapp.com

publish_mode: editorial_workflow
media_folder: "assets/uploaded"

collections:
  - name: "events"
    label: "Events"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Event date", name: "date", widget: "datetime"}
      - {label: "Booked out", name: "booked_out", widget: "boolean"}
      - label: "Host information"
        name: "host"
        widget: "object"
        fields:
          - {label: "Host image", name: "image", widget: "image"}
          - {label: "Host name", name: "name", widget: "string"}
          - {label: "Blurb", name: "blurb", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone number", name: "phone", widget: "string"}
          - {label: "Website (remember http://)", name: "website", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tag"
        widget: "list"
        allow_add: false
        default: []