backend:
  name: github
  repo: Wellington-Heritage-Week/Wellington-Heritage-Week.github.io
  branch: master
  base_url: https://wellington-heritage-week.herokuapp.com

publish_mode: editorial_workflow
media_folder: "assets/uploaded"

collections:
  - name: "events"
    label: "Events"
    folder: "_collections/_events/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {required: false, label: "Title", name: "title", widget: "string"}
      - {required: true, label: "Location", name: "location", widget: "string", default: "Wellington City"}
      - {required: false, label: "Short description (for facebook)", name: "description", widget: "text"}
      - {required: false, label: "Image", name: "img", widget: "image"}
      - {required: false, label: "Event date", name: "event_date", widget: "string"}
      - {required: false, label: "Sold Out", name: "booked_out", widget: "boolean"}
      - {required: false, label: "Book Promotion", name: "book_promotion", widget: "boolean"}
      - {required: false, label: "Hotel", name: "hotel", widget: "boolean"}
      - {required: false, label: "Hotel summary", name: "hotel_text", widget: "markdown"}
      - {required: false, label: "Hotel availability", name: "availability_text", widget: "markdown"}
      - label: "Host information"
        name: "host"
        widget: "object"
        fields:
          - {required: false, label: "Host image", name: "image", widget: "image"}
          - {required: false, label: "Host name", name: "name", widget: "string"}
          - {required: false, label: "Blurb", name: "blurb", widget: "string"}
          - {required: false, label: "Email", name: "email", widget: "string"}
          - {required: false, label: "Phone number", name: "phone", widget: "string"}
          - {required: false, label: "Website (remember http://)", name: "website", widget: "string"}
      - {required: false, label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tag"
        widget: "list"
        allow_add: false
        default: []
        - name: "events"
    label: "hotel"
    folder: "_collections/_hotel/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {required: false, label: "Title", name: "title", widget: "string"}
      - {required: true, label: "Location", name: "location", widget: "string", default: "Wellington City"}
      - {required: false, label: "Short description (for facebook)", name: "description", widget: "text"}
      - {required: false, label: "Image", name: "img", widget: "image"}
      - {required: false, label: "Event date", name: "event_date", widget: "string"}
      - {required: false, label: "Sold Out", name: "booked_out", widget: "boolean"}
      - {required: false, label: "Book Promotion", name: "book_promotion", widget: "boolean"}
      - {required: false, label: "Hotel", name: "hotel", widget: "boolean"}
      - {required: false, label: "Hotel summary", name: "hotel_text", widget: "markdown"}
      - {required: false, label: "Hotel availability", name: "availability_text", widget: "markdown"}
      - label: "Host information"
        name: "host"
        widget: "object"
        fields:
          - {required: false, label: "Host image", name: "image", widget: "image"}
          - {required: false, label: "Host name", name: "name", widget: "string"}
          - {required: false, label: "Blurb", name: "blurb", widget: "string"}
          - {required: false, label: "Email", name: "email", widget: "string"}
          - {required: false, label: "Phone number", name: "phone", widget: "string"}
          - {required: false, label: "Website (remember http://)", name: "website", widget: "string"}
      - {required: false, label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tag"
        widget: "list"
        allow_add: false
        default: []
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site settings"
        name: "site"
        file: "_data/settings.yml"
        fields:
          - {required: false, label: "Site title", name: "title", widget: "text"}
          - {required: false, label: "Site description (google search)", name: "description", widget: "text"}
          - {required: false, label: "Analytics tracking tag", name: "analytics", widget: "text"}
          - {required: false, label: "Show events", name: "show_events", widget: "boolean"}
          - {required: false, label: "Show hotel", name: "show_hotel", widget: "boolean"}
          - {required: false, label: "Homepage title", name: "banner-title", widget: "text"}
          - {required: false, label: "Default social image (facebook etc..)", name: "banner", widget: "image"}
      - label: "Social media settings"
        name: "social"
        file: "_data/social.yml"
        fields:
          - {required: false, label: "Facebook url", name: "facebook_url", widget: "text"}
          - {required: false, label: "Instagram url", name: "instagram_url", widget: "text"}
      - label: "About page settings"
        name: "about"
        file: "_data/about.yml"
        fields:
          - {required: false, label: "Author image", name: "author-pic", widget: "image"}
          - {required: false, label: "Author name", name: "author-name", widget: "text"}
          - {required: false, label: "Author about", name: "about-author", widget: "text"}
      - label: "Contact settings"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {required: false, label: "Email", name: "email", widget: "text"}
          - {required: false, label: "Phone", name: "phone", widget: "text"}
          - {required: false, label: "Website", name: "website", widget: "text"}
      - label: "Sponsors"
        name: "sponsors"
        file: "_data/sponsors.yml"
        fields:
          - label: "Sponsors"
            name: "sponsors"
            widget: "list"
            fields:
              - label: "Sponsor name"
                name: "name"
                widget: "text"
              - label: "Sponsor logo"
                name: "logo"
                widget: "image"
      - label: "Background Images"
        name: "background"
        file: "_data/backgrounds.yml"
        fields:
          - label: "Rollover time (milliseconds)"
            name: "rollover_time"
            widget: "number"
            min: 1000
            valueType: "int"
          - label: "Background Images"
            name: "images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
